# Generated by Django 3.2.7 on 2021-11-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
