# Generated by Django 3.2.7 on 2021-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('faculty_name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=5)),
                ('midterm', models.CharField(max_length=5)),
                ('finals', models.CharField(max_length=5)),
                ('finalgrade', models.CharField(max_length=5)),
            ],
        ),
    ]
