# Generated by Django 3.2.6 on 2021-12-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='DonationSource',
        ),
    ]
