# Generated by Django 3.2.7 on 2021-11-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student',
            new_name='username',
        ),
    ]
