# Generated by Django 3.2.7 on 2021-11-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0002_grades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
    ]
