# Generated by Django 3.2.7 on 2021-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0003_rename_grades_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gv_code', models.IntegerField()),
            ],
        ),
    ]
