# Generated by Django 3.2.7 on 2021-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0003_rename_student_grade_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusivevoucher',
            name='ev_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
