# Generated by Django 3.2.7 on 2021-11-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0004_exclusivevoucher_ev_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivevoucher',
            name='ev_grade',
        ),
    ]
