# Generated by Django 3.2.7 on 2021-11-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdev', '0004_exclusivevoucher_generalvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='finalgrade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='finals',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='units',
            field=models.FloatField(),
        ),
    ]
